# Classification

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk

## Step1: read data as dataframe


In [2]:
df=pd.read_csv("breast_cancer.csv")

In [3]:
df=df.iloc[:,:-1]

In [4]:
df.shape

(569, 32)

In [5]:
x=df.iloc[:,2:].values
y=df.diagnosis.values

In [6]:
print(x[:5])
print(y[:5])

[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 3.861e+02 1.425e-01 2.839e-01 2.414

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=500)

In [9]:
x_train.shape

(455, 30)

In [10]:
x_test.shape

(114, 30)

In [11]:
y_train.shape

(455,)

In [12]:
y_test.shape

(114,)

In [13]:
(y_train == 'M').sum()

177

In [14]:
(y_train=='B').sum()

278

 # Baseline model, accuracy, confusion_matrix, classification_report

In [15]:
278/len(y_train)  # Baseline model of accuracy =(more number of occurrences)/total data elements

0.610989010989011

In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [17]:
baseline_pred=["B"] *len(y_train) # baseline will have beningn for everything

In [18]:
accuracy_score(y_train,baseline_pred) # takes actual and predicted as 2 arguments

0.610989010989011

In [19]:
confusion_matrix(y_train,baseline_pred)# takes actual and predicted as 2 arguments

array([[278,   0],
       [177,   0]], dtype=int64)

In [20]:
print(classification_report(y_train,baseline_pred))

             precision    recall  f1-score   support

          B       0.61      1.00      0.76       278
          M       0.00      0.00      0.00       177

avg / total       0.37      0.61      0.46       455



C:\Users\123\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


## NAIVE BAYES ALGORITHM

In [21]:
from sklearn.naive_bayes import GaussianNB

In [22]:
nb_model=GaussianNB()

In [23]:
nb_model.fit(x_train,y_train)

GaussianNB(priors=None)

In [24]:
print(x_train)

[[1.959e+01 1.815e+01 1.307e+02 ... 2.247e-01 3.643e-01 9.223e-02]
 [1.132e+01 2.708e+01 7.176e+01 ... 2.083e-02 2.849e-01 7.087e-02]
 [9.173e+00 1.386e+01 5.920e+01 ... 5.087e-02 3.282e-01 8.490e-02]
 ...
 [1.481e+01 1.470e+01 9.466e+01 ... 7.955e-02 2.334e-01 6.142e-02]
 [1.289e+01 1.312e+01 8.189e+01 ... 5.366e-02 2.309e-01 6.915e-02]
 [9.742e+00 1.567e+01 6.150e+01 ... 5.159e-02 2.841e-01 8.175e-02]]


In [25]:
nb_model.score(x_train,y_train)

0.9318681318681319

In [26]:
nb_model.score(x_test,y_test)

0.9736842105263158

In [27]:
#confusion_matrix for training data
confusion_matrix(y_train,nb_model.predict(x_train))

array([[269,   9],
       [ 22, 155]], dtype=int64)

In [28]:
#confusion_matrix for test data
confusion_matrix(y_test,nb_model.predict(x_test))

array([[78,  1],
       [ 2, 33]], dtype=int64)

In [29]:
print(classification_report(y_train,nb_model.predict(x_train)))

             precision    recall  f1-score   support

          B       0.92      0.97      0.95       278
          M       0.95      0.88      0.91       177

avg / total       0.93      0.93      0.93       455



In [30]:
print(classification_report(y_test,nb_model.predict(x_test)))

             precision    recall  f1-score   support

          B       0.97      0.99      0.98        79
          M       0.97      0.94      0.96        35

avg / total       0.97      0.97      0.97       114



In [31]:
nb_model.predict_proba(x_train) # benign>0.5 otherwise if <0.5 then malignant{ first column is benign and secon is malignant according to aplphanumerical order}

array([[5.15394378e-089, 1.00000000e+000],
       [1.00000000e+000, 1.23384611e-014],
       [1.00000000e+000, 1.04492460e-014],
       [5.53047988e-092, 1.00000000e+000],
       [4.19425529e-008, 9.99999958e-001],
       [1.00000000e+000, 3.26215300e-012],
       [3.12139891e-008, 9.99999969e-001],
       [1.00000000e+000, 1.72293019e-015],
       [9.99999874e-001, 1.25536020e-007],
       [1.00000000e+000, 1.18064642e-013],
       [9.99687919e-001, 3.12080857e-004],
       [2.71657827e-014, 1.00000000e+000],
       [1.00000000e+000, 8.48695935e-014],
       [9.40640486e-001, 5.93595141e-002],
       [8.19514119e-079, 1.00000000e+000],
       [3.83541561e-005, 9.99961646e-001],
       [6.06067220e-027, 1.00000000e+000],
       [9.16899161e-005, 9.99908310e-001],
       [1.00000000e+000, 1.30606139e-012],
       [9.99999999e-001, 1.15702285e-009],
       [1.00000000e+000, 2.29040675e-013],
       [1.00000000e+000, 5.73580073e-014],
       [5.98443895e-253, 1.00000000e+000],
       [1.0

In [32]:
nb_model.predict(x_train)[:5]

array(['M', 'B', 'B', 'M', 'M'], dtype='<U1')

In [33]:
np.set_printoptions(suppress= True)
nb_model.predict_proba(x_train)[:5]

array([[0.        , 1.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [0.00000004, 0.99999996]])

In [34]:
nb_model.predict_proba(x_train)[:,1]>0.4

array([ True, False, False,  True,  True, False,  True, False, False,
       False, False,  True, False, False,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True, False,  True,
        True,  True, False, False, False, False, False, False,  True,
       False,  True,  True, False, False, False, False,  True,  True,
       False, False, False, False,  True,  True, False,  True, False,
       False, False, False,  True,  True, False, False,  True, False,
       False, False, False, False,  True, False, False, False, False,
       False, False,  True,  True, False,  True, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False,  True, False, False, False,  True, False,
        True, False, False, False, False, False,  True, False, False,
        True,  True, False,  True, False, False, False,  True, False,
       False,  True, False, False, False, False, False,  True,  True,
        True, False,

In [35]:
pred=nb_model.predict_proba(x_train)[:,1] >0.25

In [36]:
confusion_matrix(y_train =='M',pred)

array([[268,  10],
       [ 19, 158]], dtype=int64)

In [37]:
test_pred=nb_model.predict_proba(x_test)[:,1] >0.25

In [39]:
confusion_matrix(y_test =='M',test_pred)

array([[78,  1],
       [ 2, 33]], dtype=int64)